#!/bin/sh
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Foreca
echo "###################################################"
echo "#                                                 #"
echo "#           Foreca successfully removed           #"
echo "#           Please restart enigma2 now!           #"
echo "#                                                 #"
echo "###################################################"
exit 0
