#!/bin/sh
echo "###################################################"
echo "#                                                 #"
echo "#         Foreca successfully installed!          #"
echo "#         Please restart enigma2                  #"
echo "#                                                 #"
echo "###################################################"
exit 0